name: 'fast-rss-translator'
description: 'fast-rss-translator'
inputs:
  config_file:
    description: 'rss configuration file'
    required: true
    default: 'subscribes.yaml'
  update_file:
    description: 'update rss urls file path'
    required: true
    default: 'README.md'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --config_file=${{ inputs.config_file }}
    - --update_file=${{ inputs.update_file }}
