name: test_github_action

on:
  schedule: # 3:00 UTC
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  test_fast_rss_translator_action:
    runs-on: ubuntu-latest
    name: test fast-rss-translator action
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: fast-rss-translator
        uses: ./
        id: fast-rss-translator-action
        with:
          update_file: 'README.md'
          push: true
          username: "github-actions[bot]"
          org: "yeshan333"
          repo: "fast-rss-translator"
          token: ${{ secrets.GITHUB_TOKEN }}
