name: test_github_action

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:

permissions:
  contents: write

jobs:
  test_fast_rss_translator_action:
    runs-on: ubuntu-latest
    name: test fast-rss-translator action
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: fast-rss-translator
        uses: ./
        id: fast-rss-translator-action
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
        with:
          config_file: 'subscribes.yaml'
          update_file: 'TEST_README.md'
          push: true
          username: "github-actions[bot]"
          org: "yeshan333"
          repo: "fast-rss-translator"
          token: ${{ secrets.GITHUB_TOKEN }}
