name: test_github_action

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:

permissions:                    # Global permissions configuration starts here
  contents: read                # 'read' access to repository contents
  pull-requests: write          # 'write' access to pull requests

jobs:
  test_fast_rss_translator_action:
    runs-on: ubuntu-latest
    name: test fast-rss-translator action
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: fast-rss-translator
        uses: ./
        id: fast-rss-translator-action
        with:
          config_file: 'subscribes.yaml'
          update_file: 'TEST_README.md'
          cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare_api_key: ${{ secrets.CLOUDFLARE_API_KEY }}
      - name: Commit rss files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Update rss files"
      - name: Push rss changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}