name: translate_timer

on:
  schedule: # 3:00 UTC
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  do_rss_tranaslte:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.22.4'

      - name: Do translate
        run: |
          go run main.go --update-file README.md

      - name: Push translated rss
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .

          git commit -m "Auto commit by bot, ci skip"
          git push